server:
  port: 8085

jpa:
  defer-datasource-initialization: true
  hibernate:
    ddl-auto: none

spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:users
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: true
    drop-first: false
    change-log: http://www.liquibase.org/xml/ns/dbchangelog
    default-schema: public