server:
  port: 8085

jpa:
  defer-datasource-initialization: true
  hibernate:
    ddl-auto: none

spring:
  datasource:
    url: jdbc:postgresql://188.235.13.36:5432/users
    username: selectel
    password: selectel
    driverClassName: org.postgresql.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    drop-first: false
    change-log: config\db\changelog\changelog.xml
    default-schema: public