server:
  port: 8085

jpa:
  defer-datasource-initialization: true
  hibernate:
    ddl-auto: none

spring:
  application:
    name: users_ms
  datasource:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect

liquibase:
  enabled: true
  drop-first: false
  default-schema: public

eureka:
  client:
    service-url:
      defaultZone: http://188.235.13.36/eureka